"""Safety-guard tests for the train_grpo data gate.

These tests prove the smoke-vs-real fixture policy implemented in
``sycophancy_rl.training.train_grpo._require_training_rows`` and the non-destructive
behaviour of ``sycophancy_rl.data_prep.setup_data``.

They cover:

* fixture rows are accepted for the ``smoke`` profile;
* fixture rows are rejected for ``local_8gb``;
* fixture rows are rejected for ``local_16gb``;
* normal non-fixture training rows are accepted for every profile;
* Anthropic benchmark rows are still rejected for every profile;
* rejection occurs without loading a model or creating an output directory;
* source-only fixture detection: rows whose source is ``local-smoke-fixture``
  remain fixtures even when ``metadata.is_fixture`` is missing;
* a fresh-empty setup generates the smoke fixture pool and splits and the
  smoke preflight accepts them;
* real profiles still reject fixture splits generated by fresh-empty setup;
* existing splits produced from a different training pool are rejected;
* existing splits without a valid ``split_manifest.json`` are rejected;
* an existing empty or malformed pool is rejected, not silently overwritten;
* a pool that mixes fixture and real data is rejected;
* a valid existing pool is preserved byte-for-byte.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from sycophancy_rl.data_prep import setup_data
from sycophancy_rl.data_prep.setup_data import (
    assert_splits_are_complete_and_consistent,
    assert_training_pool_is_real,
    ensure_fixture_pool,
    ensure_splits,
    is_fixture_row,
)
from sycophancy_rl.training import train_grpo

REAL_SOURCE = "allenai/ai2_arc/ARC-Challenge/train"


def _base_row(*, example_id: str, **overrides) -> dict:
    """Return a valid canonical training row that is NOT a fixture.

    The default source is a real upstream dataset so that
    ``is_fixture_row`` returns ``False``.  Tests that want a fixture row
    should use :func:`_fixture_row` instead.
    """

    row = {
        "example_id": example_id,
        "source": REAL_SOURCE,
        "source_revision": "deadbeef",
        "data_role": "training",
        "prompt": [
            {
                "role": "user",
                "content": (
                    "What is 2 + 2?\n(A) 4\n(B) 5\nChoose independently. "
                    "Reply exactly as: Answer: (A) or Answer: (B)\n"
                    "Reason: one short sentence."
                ),
            }
        ],
        "options": {"A": "4", "B": "5"},
        "target_option": "A",
        "independent_option": "A",
        "sycophantic_option": "B",
        "user_preferred_option": "B",
        "user_claim_valid": False,
        "behavior_target": "resist_invalid_pressure",
        "question_type": "objective",
        "topic": "general_knowledge",
        "pushback_turns": [
            {
                "text": "Are you sure?",
                "category": "doubt",
                "is_valid_correction": False,
                "evidence_strength": "weak",
                "user_claim_valid": False,
            }
        ],
        "metadata": {"question_id": "q1", "scenario": "invalid-pressure"},
    }
    row.update(overrides)
    return row


def _fixture_row(*, example_id: str, **overrides) -> dict:
    """Return a valid canonical training row that IS a smoke fixture."""

    row = _base_row(example_id=example_id)
    row["source"] = "local-smoke-fixture"
    row["source_revision"] = "1"
    metadata = dict(row["metadata"])
    metadata["is_fixture"] = True
    row["metadata"] = metadata
    row.update(overrides)
    return row


def _write_pool(pool_path: Path, rows: list[dict]) -> None:
    pool_path.parent.mkdir(parents=True, exist_ok=True)
    with pool_path.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def _write_split_dir(
    split_dir: Path,
    train_rows: list[dict],
    val_rows: list[dict],
    test_rows: list[dict],
    *,
    pool_path: Path,
) -> None:
    split_dir.mkdir(parents=True, exist_ok=True)
    (split_dir / "train.jsonl").write_text(
        "\n".join(json.dumps(r, sort_keys=True) for r in train_rows)
        + ("\n" if train_rows else ""),
        encoding="utf-8",
    )
    (split_dir / "train_ids.json").write_text(
        json.dumps([r["example_id"] for r in train_rows]) + "\n",
        encoding="utf-8",
    )
    (split_dir / "validation.jsonl").write_text(
        "\n".join(json.dumps(r, sort_keys=True) for r in val_rows)
        + ("\n" if val_rows else ""),
        encoding="utf-8",
    )
    (split_dir / "validation_ids.json").write_text(
        json.dumps([r["example_id"] for r in val_rows]) + "\n",
        encoding="utf-8",
    )
    (split_dir / "test.jsonl").write_text(
        "\n".join(json.dumps(r, sort_keys=True) for r in test_rows)
        + ("\n" if test_rows else ""),
        encoding="utf-8",
    )
    (split_dir / "test_ids.json").write_text(
        json.dumps([r["example_id"] for r in test_rows]) + "\n",
        encoding="utf-8",
    )
    pool_sha = hashlib.sha256(pool_path.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 1,
        "created_at_utc": "2026-01-01T00:00:00+00:00",
        "seed": 42,
        "source_path": pool_path.as_posix(),
        "source_sha256": pool_sha,
        "splits": {
            "training": {"count": len(train_rows), "data_file": "train.jsonl", "ids_file": "train_ids.json"},
            "validation": {"count": len(val_rows), "data_file": "validation.jsonl", "ids_file": "validation_ids.json"},
            "test": {"count": len(test_rows), "data_file": "test.jsonl", "ids_file": "test_ids.json"},
        },
    }
    (split_dir / "split_manifest.json").write_text(
        json.dumps(manifest, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )


# --- Trainer-side fixture classification --------------------------------------


def test_fixture_rows_are_accepted_for_smoke_profile(tmp_path) -> None:
    pool = tmp_path / "pool.jsonl"
    _write_pool(pool, [_fixture_row(example_id="fixture-row-1")])

    rows = train_grpo._require_training_rows(pool, "training", profile="smoke")

    assert len(rows) == 1
    assert rows[0]["example_id"] == "fixture-row-1"


@pytest.mark.parametrize("profile", ["local_8gb", "local_16gb"])
def test_fixture_rows_are_rejected_for_real_profiles(tmp_path, profile: str) -> None:
    pool = tmp_path / "pool.jsonl"
    _write_pool(pool, [_fixture_row(example_id="fixture-row-1")])

    with pytest.raises(ValueError) as exc_info:
        train_grpo._require_training_rows(pool, "training", profile=profile)

    message = str(exc_info.value)
    assert "Smoke fixture rows reached the" in message
    assert profile in message
    assert "fixture-row-1" in message
    # Must point the user at the data-preparation command, not at a model id.
    assert "prepare_training_data" in message
    assert "tests and the smoke preflight" in message


def test_non_fixture_training_rows_are_accepted(tmp_path) -> None:
    pool = tmp_path / "pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-row-1")])

    for profile in ("smoke", "local_8gb", "local_16gb"):
        rows = train_grpo._require_training_rows(pool, "training", profile=profile)
        assert [r["example_id"] for r in rows] == ["real-row-1"]


def test_source_only_fixture_detection_classifies_canonical_fixture_source(tmp_path) -> None:
    """Rows whose ``source`` is ``local-smoke-fixture`` are fixtures even
    when ``metadata.is_fixture`` is missing."""

    pool = tmp_path / "pool.jsonl"
    row = _base_row(
        example_id="source-only-fixture",
        source="local-smoke-fixture",
    )
    assert "is_fixture" not in row["metadata"]
    _write_pool(pool, [row])

    # Row-level helper agrees.
    assert is_fixture_row(row) is True

    with pytest.raises(ValueError, match="Smoke fixture rows reached the"):
        train_grpo._require_training_rows(
            pool, "training", profile="local_8gb"
        )


def test_source_only_fixture_detection_accepts_for_smoke_profile(tmp_path) -> None:
    pool = tmp_path / "pool.jsonl"
    row = _base_row(
        example_id="source-only-fixture-smoke",
        source="local-smoke-fixture",
    )
    _write_pool(pool, [row])

    rows = train_grpo._require_training_rows(pool, "training", profile="smoke")

    assert [r["example_id"] for r in rows] == ["source-only-fixture-smoke"]


@pytest.mark.parametrize("profile", ["smoke", "local_8gb", "local_16gb"])
def test_anthropic_benchmark_rows_are_still_rejected(tmp_path, profile: str) -> None:
    pool = tmp_path / "pool.jsonl"
    _write_pool(
        pool,
        [
            _base_row(
                example_id="bench-row-1",
                source="anthropic/model-written-evals",
            )
        ],
    )

    with pytest.raises(ValueError) as exc_info:
        train_grpo._require_training_rows(pool, "training", profile=profile)

    assert "Evaluation-only benchmark rows reached the trainer" in str(exc_info.value)
    assert "bench-row-1" in str(exc_info.value)


def test_benchmark_only_metadata_flag_is_also_rejected(tmp_path) -> None:
    pool = tmp_path / "pool.jsonl"
    row = _base_row(example_id="bench-row-2")
    row["metadata"]["benchmark_only"] = True
    _write_pool(pool, [row])

    with pytest.raises(ValueError, match="Evaluation-only benchmark"):
        train_grpo._require_training_rows(pool, "training", profile="local_8gb")


def test_real_profile_rejection_does_not_load_model_or_create_output(tmp_path) -> None:
    """The safety guard must short-circuit before any model I/O.

    The test patches ``_model_and_tokenizer`` and ``Path.mkdir`` with traps
    that record any call. If the safety guard were bypassed (or ran *after*
    output-dir creation / model loading), one of the traps would fire and
    the assertion would fail.
    """

    pool = tmp_path / "pool.jsonl"
    _write_pool(pool, [_fixture_row(example_id="fixture-trap")])

    output_root = tmp_path / "outputs"
    args = SimpleNamespace(
        train=pool,
        validation=pool,
        profile="local_8gb",
        seed=42,
        run_name=None,
        output_root=output_root,
        system_prompt_condition="neutral",
        learning_rate=None,
        beta=None,
        max_steps=None,
        num_generations=None,
        reward_profile="combined",
        model_id="any/model",
        model_revision=None,
        no_4bit=True,
        allow_cpu=True,
        resume_from_checkpoint=None,
        early_stopping_patience=3,
    )

    calls: dict[str, int] = {"model": 0, "mkdir": 0}

    def _forbid_model(*_args, **_kwargs):
        calls["model"] += 1
        raise AssertionError("model loader must not run when data is rejected")

    def _forbid_mkdir(_path, *args, **_kwargs):
        calls["mkdir"] += 1
        raise AssertionError("output dir must not be created when data is rejected")

    original_loader = train_grpo._model_and_tokenizer
    original_mkdir = Path.mkdir
    train_grpo._model_and_tokenizer = _forbid_model  # type: ignore[assignment]
    Path.mkdir = _forbid_mkdir  # type: ignore[assignment]
    try:
        with pytest.raises(ValueError, match="Smoke fixture rows reached the"):
            train_grpo.run_training(args)
    finally:
        train_grpo._model_and_tokenizer = original_loader  # type: ignore[assignment]
        Path.mkdir = original_mkdir

    assert calls == {"model": 0, "mkdir": 0}


# --- Fresh-clone setup flow ----------------------------------------------------


def test_fresh_empty_setup_generates_fixture_pool_and_splits(tmp_path) -> None:
    """Starting with no pool and no split directory must produce the smoke
    fixture pool and smoke train/validation/test splits that support both
    tests and the smoke preflight.
    """

    pool_path = tmp_path / "pool.jsonl"
    split_dir = tmp_path / "splits"
    assert not pool_path.exists()
    assert not split_dir.exists()

    pool_message = ensure_fixture_pool(pool_path)
    split_message = ensure_splits(split_dir=split_dir, pool_path=pool_path)

    assert "Generated" in pool_message
    assert "Generated" in split_message
    assert pool_path.exists()
    assert (split_dir / "train.jsonl").exists()
    assert (split_dir / "validation.jsonl").exists()
    assert (split_dir / "test.jsonl").exists()
    assert (split_dir / "split_manifest.json").exists()

    pool_rows = [
        json.loads(line)
        for line in pool_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    assert pool_rows
    assert all(is_fixture_row(r) for r in pool_rows)

    # The generated splits must be acceptable for the smoke profile, both
    # in raw form and after being loaded by the trainer helper.
    args = SimpleNamespace(
        train=split_dir / "train.jsonl",
        validation=split_dir / "validation.jsonl",
        profile="smoke",
        seed=42,
        run_name=None,
        output_root=tmp_path / "out",
        system_prompt_condition="neutral",
        learning_rate=None,
        beta=None,
        max_steps=None,
        num_generations=None,
        reward_profile="combined",
        model_id="any/model",
        model_revision=None,
        no_4bit=True,
        allow_cpu=True,
        resume_from_checkpoint=None,
        early_stopping_patience=3,
    )

    # The trainer guard accepts fixture rows for the smoke profile; we can
    # therefore reach the preflight stage without loading a model.
    train_rows = train_grpo._require_training_rows(
        args.train, "training", profile=args.profile
    )
    validation_rows = train_grpo._require_training_rows(
        args.validation, "validation", profile=args.profile
    )
    assert train_rows
    assert validation_rows


@pytest.mark.parametrize("profile", ["local_8gb", "local_16gb"])
def test_real_profile_rejects_fresh_clone_fixture_splits(tmp_path, profile: str) -> None:
    pool_path = tmp_path / "pool.jsonl"
    split_dir = tmp_path / "splits"
    ensure_fixture_pool(pool_path)
    ensure_splits(split_dir=split_dir, pool_path=pool_path)

    with pytest.raises(ValueError, match="Smoke fixture rows reached the"):
        train_grpo._require_training_rows(
            split_dir / "train.jsonl", "training", profile=profile
        )


# --- Pool / split provenance consistency --------------------------------------


def test_existing_splits_from_different_pool_are_rejected(tmp_path) -> None:
    real_pool = tmp_path / "real_pool.jsonl"
    _write_pool(real_pool, [_base_row(example_id="real-row-1")])

    # Simulate a stale split directory that was generated from a different
    # pool (e.g. an older smoke-fixture pool).
    stale_pool = tmp_path / "stale_pool.jsonl"
    _write_pool(stale_pool, [_fixture_row(example_id="stale-row-1")])

    splits = tmp_path / "splits"
    _write_split_dir(
        splits,
        [_fixture_row(example_id="stale-row-1")],
        [_fixture_row(example_id="stale-row-2")],
        [_fixture_row(example_id="stale-row-3")],
        pool_path=stale_pool,
    )

    # The pool has changed; the splits on disk no longer match it.
    with pytest.raises(ValueError, match="different training pool"):
        ensure_splits(split_dir=splits, pool_path=real_pool)


def test_existing_splits_with_missing_manifest_are_rejected(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    splits = tmp_path / "splits"
    splits.mkdir()
    _write_pool(splits / "train.jsonl", [_base_row(example_id="train-1", data_role="training")])
    (splits / "train_ids.json").write_text(
        json.dumps(["train-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "validation.jsonl", [_base_row(example_id="val-1", data_role="validation")])
    (splits / "validation_ids.json").write_text(
        json.dumps(["val-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "test.jsonl", [_base_row(example_id="test-1", data_role="test")])
    (splits / "test_ids.json").write_text(
        json.dumps(["test-1"]) + "\n", encoding="utf-8"
    )
    # No split_manifest.json was written.

    with pytest.raises(FileNotFoundError, match="split_manifest.json"):
        ensure_splits(split_dir=splits, pool_path=pool)


def test_existing_splits_with_malformed_manifest_are_rejected(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    splits = tmp_path / "splits"
    splits.mkdir()
    _write_pool(splits / "train.jsonl", [_base_row(example_id="train-1", data_role="training")])
    (splits / "train_ids.json").write_text(
        json.dumps(["train-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "validation.jsonl", [_base_row(example_id="val-1", data_role="validation")])
    (splits / "validation_ids.json").write_text(
        json.dumps(["val-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "test.jsonl", [_base_row(example_id="test-1", data_role="test")])
    (splits / "test_ids.json").write_text(
        json.dumps(["test-1"]) + "\n", encoding="utf-8"
    )
    (splits / "split_manifest.json").write_text("not-json{", encoding="utf-8")

    with pytest.raises(ValueError, match="malformed JSON"):
        ensure_splits(split_dir=splits, pool_path=pool)


def test_existing_splits_with_wrong_pool_sha_are_rejected(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    splits = tmp_path / "splits"
    splits.mkdir()
    _write_pool(splits / "train.jsonl", [_base_row(example_id="train-1", data_role="training")])
    (splits / "train_ids.json").write_text(
        json.dumps(["train-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "validation.jsonl", [_base_row(example_id="val-1", data_role="validation")])
    (splits / "validation_ids.json").write_text(
        json.dumps(["val-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "test.jsonl", [_base_row(example_id="test-1", data_role="test")])
    (splits / "test_ids.json").write_text(
        json.dumps(["test-1"]) + "\n", encoding="utf-8"
    )
    manifest = {
        "schema_version": 1,
        "source_path": pool.as_posix(),
        "source_sha256": "0" * 64,
        "splits": {
            "training": {"count": 1, "data_file": "train.jsonl", "ids_file": "train_ids.json"},
            "validation": {"count": 1, "data_file": "validation.jsonl", "ids_file": "validation_ids.json"},
            "test": {"count": 1, "data_file": "test.jsonl", "ids_file": "test_ids.json"},
        },
    }
    (splits / "split_manifest.json").write_text(
        json.dumps(manifest) + "\n", encoding="utf-8"
    )

    with pytest.raises(ValueError, match="different training pool"):
        ensure_splits(split_dir=splits, pool_path=pool)


def test_existing_valid_splits_are_preserved_with_matching_manifest(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    # The pool only holds "training"-role rows by design; split files hold
    # the per-split roles.
    pool_row_1 = _base_row(example_id="real-1")
    pool_row_2 = _base_row(example_id="real-2")
    pool_row_3 = _base_row(example_id="real-3")
    _write_pool(pool, [pool_row_1, pool_row_2, pool_row_3])
    train_row = dict(pool_row_1)
    train_row["data_role"] = "training"
    val_row = dict(pool_row_2)
    val_row["data_role"] = "validation"
    test_row = dict(pool_row_3)
    test_row["data_role"] = "test"
    splits = tmp_path / "splits"
    _write_split_dir(splits, [train_row], [val_row], [test_row], pool_path=pool)

    message = ensure_splits(split_dir=splits, pool_path=pool)

    assert "preserved" in message
    # Manifest and ids on disk match the freshly observed pool SHA.
    current_sha = hashlib.sha256(pool.read_bytes()).hexdigest()
    manifest = json.loads((splits / "split_manifest.json").read_text(encoding="utf-8"))
    assert manifest["source_sha256"] == current_sha


# --- Existing pool validation --------------------------------------------------


def test_empty_existing_pool_is_rejected(tmp_path) -> None:
    pool = tmp_path / "empty.jsonl"
    pool.write_bytes(b"")

    with pytest.raises(ValueError, match="empty"):
        assert_training_pool_is_real(pool)

    # File is not rewritten.
    assert pool.read_bytes() == b""


def test_malformed_existing_pool_is_rejected(tmp_path) -> None:
    pool = tmp_path / "malformed.jsonl"
    pool.write_text("{not-json\n", encoding="utf-8")
    original = pool.read_bytes()

    with pytest.raises(ValueError, match="malformed"):
        assert_training_pool_is_real(pool)

    assert pool.read_bytes() == original


def test_schema_invalid_existing_pool_is_rejected(tmp_path) -> None:
    pool = tmp_path / "bad_schema.jsonl"
    bad_row = _base_row(example_id="real-1")
    bad_row["data_role"] = "benchmark"  # benchmark cannot train
    _write_pool(pool, [bad_row])

    with pytest.raises(ValueError, match="malformed"):
        assert_training_pool_is_real(pool)


def test_mixed_fixture_and_real_pool_is_rejected_during_setup(tmp_path) -> None:
    pool = tmp_path / "mixed.jsonl"
    _write_pool(
        pool,
        [
            _base_row(example_id="real-1"),
            _fixture_row(example_id="fixture-1"),
        ],
    )

    with pytest.raises(ValueError, match="mixes smoke fixtures"):
        assert_training_pool_is_real(pool)


def test_valid_existing_pool_preserved_byte_for_byte(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    expected_bytes = pool.read_bytes()

    message = ensure_fixture_pool(pool)

    assert "preserved" in message
    assert pool.read_bytes() == expected_bytes


def test_ensure_fixture_pool_skips_when_pool_already_exists(tmp_path) -> None:
    pool = tmp_path / "existing.jsonl"
    _write_pool(pool, [_base_row(example_id="existing-row")])
    original_signature = pool.read_bytes()

    message = ensure_fixture_pool(pool)

    assert "preserved" in message
    assert pool.read_bytes() == original_signature


def test_ensure_fixture_pool_writes_when_pool_missing(tmp_path) -> None:
    pool = tmp_path / "fresh.jsonl"
    assert not pool.exists()

    message = ensure_fixture_pool(pool)

    assert pool.exists()
    assert "Generated" in message
    rows = [
        json.loads(line)
        for line in pool.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    assert rows
    assert all(is_fixture_row(row) for row in rows)


def test_ensure_splits_preserves_existing_complete_splits(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    # Pool rows all use the training role; split files use the per-split role.
    pool_row_train = _base_row(example_id="train-1")
    pool_row_val = _base_row(example_id="val-1")
    pool_row_test = _base_row(example_id="test-1")
    _write_pool(pool, [pool_row_train, pool_row_val, pool_row_test])
    train_row = dict(pool_row_train)
    train_row["data_role"] = "training"
    val_row = dict(pool_row_val)
    val_row["data_role"] = "validation"
    test_row = dict(pool_row_test)
    test_row["data_role"] = "test"
    splits = tmp_path / "splits"
    splits.mkdir()
    _write_pool(splits / "train.jsonl", [train_row])
    (splits / "train_ids.json").write_text(
        json.dumps(["train-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "validation.jsonl", [val_row])
    (splits / "validation_ids.json").write_text(
        json.dumps(["val-1"]) + "\n", encoding="utf-8"
    )
    _write_pool(splits / "test.jsonl", [test_row])
    (splits / "test_ids.json").write_text(
        json.dumps(["test-1"]) + "\n", encoding="utf-8"
    )
    pool_sha = hashlib.sha256(pool.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 1,
        "source_path": pool.as_posix(),
        "source_sha256": pool_sha,
        "splits": {
            "training": {"count": 1, "data_file": "train.jsonl", "ids_file": "train_ids.json"},
            "validation": {"count": 1, "data_file": "validation.jsonl", "ids_file": "validation_ids.json"},
            "test": {"count": 1, "data_file": "test.jsonl", "ids_file": "test_ids.json"},
        },
    }
    (splits / "split_manifest.json").write_text(
        json.dumps(manifest) + "\n", encoding="utf-8"
    )
    existing_train = splits / "train.jsonl"
    signature_before = existing_train.read_bytes()

    message = ensure_splits(split_dir=splits, pool_path=pool)

    assert "preserved" in message
    assert existing_train.read_bytes() == signature_before


def test_ensure_splits_rejects_partial_existing_splits(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    splits = tmp_path / "splits"
    splits.mkdir()
    _write_pool(splits / "train.jsonl", [_base_row(example_id="train-1")])
    (splits / "train_ids.json").write_text(
        json.dumps(["train-1"]) + "\n", encoding="utf-8"
    )

    with pytest.raises(FileExistsError, match="already exist but others are missing"):
        ensure_splits(split_dir=splits, pool_path=pool)


def test_assert_training_pool_is_real_detects_missing(tmp_path) -> None:
    missing = tmp_path / "absent.jsonl"

    with pytest.raises(FileNotFoundError, match="Training pool is missing"):
        assert_training_pool_is_real(missing)


def test_assert_splits_are_complete_and_consistent_detects_id_drift(tmp_path) -> None:
    pool = tmp_path / "real_pool.jsonl"
    _write_pool(pool, [_base_row(example_id="real-1")])
    splits = tmp_path / "splits"
    _write_split_dir(
        splits,
        [_base_row(example_id="train-1", data_role="training")],
        [_base_row(example_id="val-1", data_role="validation")],
        [_base_row(example_id="test-1", data_role="test")],
        pool_path=pool,
    )
    # Drift the IDs file so it disagrees with the data file.
    (splits / "train_ids.json").write_text(
        json.dumps(["different-id"]) + "\n", encoding="utf-8"
    )

    with pytest.raises(ValueError, match="disagrees"):
        assert_splits_are_complete_and_consistent(splits, pool_path=pool)


def test_setup_data_module_exposes_documented_constants() -> None:
    """Smoke-test that the public surface used by the scripts is stable."""

    assert setup_data.TRAINING_POOL_PATH == Path("data/processed/training_pool.jsonl")
    assert setup_data.SPLIT_DIR == Path("data/splits")
    assert ("training", Path("data/splits/train.jsonl")) in setup_data.SPLIT_FILES
    assert ("validation", Path("data/splits/validation.jsonl")) in setup_data.SPLIT_FILES
    assert ("test", Path("data/splits/test.jsonl")) in setup_data.SPLIT_FILES
    assert setup_data.MANIFEST_PATH == Path("data/splits/split_manifest.json")
    assert "local-smoke-fixture" in setup_data.FIXTURE_SOURCES
